In [1]:
import numpy as np
from scipy.optimize import least_squares
from scipy.special import gamma
from dataclasses import dataclass
import pathlib as Path
import pandas as pd

In [2]:
a=np.array([1,2,3,4,5])
b=[1,2,3]
c=np.array([2,4,6,8,10])

In [3]:
b/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
np.dot(a,c)

110

In [ ]:
x=a[None,:]

In [ ]:
y=np.random.random(size=(5,5))

In [ ]:
a*y

array([[0.75030006, 0.4066994 , 1.84374351, 2.1517917 , 0.62334773],
       [0.77977542, 1.62933146, 0.5537165 , 1.8334517 , 3.56488813],
       [0.7191847 , 1.84290041, 1.84849235, 2.48752124, 1.35704092],
       [0.74735665, 1.23583009, 1.72248484, 2.87290814, 4.52805926],
       [0.59163569, 0.90415675, 0.25477412, 0.73662873, 0.13303501]])

In [ ]:
x*y

array([[0.75030006, 0.4066994 , 1.84374351, 2.1517917 , 0.62334773],
       [0.77977542, 1.62933146, 0.5537165 , 1.8334517 , 3.56488813],
       [0.7191847 , 1.84290041, 1.84849235, 2.48752124, 1.35704092],
       [0.74735665, 1.23583009, 1.72248484, 2.87290814, 4.52805926],
       [0.59163569, 0.90415675, 0.25477412, 0.73662873, 0.13303501]])